# Generated by Django 4.2.26 on 2025-11-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_company_site_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
