# Generated by Django 4.2.26 on 2025-11-23 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_alter_company_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicholiday',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='locations.country'),
        ),
        migrations.AlterField(
            model_name='publicholiday',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='locations.region'),
        ),
        migrations.AlterUniqueTogether(
            name='publicholiday',
            unique_together={('country', 'region', 'date')},
        ),
    ]
