# Generated by Django 4.2.26 on 2025-11-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_alter_publicholiday_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionalHours',
        ),
    ]
