# Generated by Django 4.2.26 on 2025-11-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_delete_regionalhours'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationException',
        ),
    ]
