# Generated by Django 4.2.26 on 2025-11-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_delete_locationexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulthours',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='defaulthours',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='defaulthours',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
