# Generated by Django 4.2.26 on 2025-11-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_country_dialing_code_country_emoji_flag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
