# Generated by Django 4.2.26 on 2025-11-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_site_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='german_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
