# Generated by Django 4.2.26 on 2025-11-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_alter_group_options_alter_company_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['location']},
        ),
        migrations.AddField(
            model_name='site',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('name', 'region')},
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('location', 'company', 'name')},
        ),
    ]
